// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz85HCuRKqrmT-OozskOOPGGhyZ9IJjn4',
    appId: '1:336276785355:web:facda4bc562fdf671a334e',
    messagingSenderId: '336276785355',
    projectId: 'yp-core-dev-us',
    authDomain: 'yp-core-dev-us.firebaseapp.com',
    storageBucket: 'yp-core-dev-us.firebasestorage.app',
    measurementId: 'G-1BE6CGVYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6_8phcs7BRecJ30KKllezOjCnNEOb4_U',
    appId: '1:336276785355:android:a2683e52927172e61a334e',
    messagingSenderId: '336276785355',
    projectId: 'yp-core-dev-us',
    storageBucket: 'yp-core-dev-us.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ01n10VcvXKXz_vQR6aEbSlxPp_Asuec',
    appId: '1:336276785355:ios:1613a0cacf902ed01a334e',
    messagingSenderId: '336276785355',
    projectId: 'yp-core-dev-us',
    storageBucket: 'yp-core-dev-us.firebasestorage.app',
    iosBundleId: 'com.yplantae.core.mod.laurus.aYpCoreModLaurusClient',
  );

}